### ISSUE TITLE
Windows link is broken

### ISSUE THREAD

**Issue by cadeyrn** [servo/download.servo.org#22] opened 2017-03-25 08:41 UTC
Hi,

there is a download link for Windows Nightly on download.servo.org since https://github.com/servo/download.servo.org/pull/20 but the link is broken (NoSuchKey error). The links for macOS and Linux still working as expected.

**Comment by ghost** [comment] 2017-03-26 09:52
Duplicate of #21

**Comment by atouchet** [comment] 2017-03-27 22:35
This was fixed in #21.

**Comment by aneeshusa** [comment] 2017-04-12 01:28
Closing as fixed by #21 (although Windows happens to be temporarily disabled again right now).

**Closed as completed by aneeshusa** 2017-04-12 01:28 UTC
